// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.fuchsia:
//       // TODO: Handle this case.
//       case TargetPlatform.linux:
//       // TODO: Handle this case.
//       case TargetPlatform.windows:
//       // TODO: Handle this case.
//     }

//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDQ33JJtQ2OTblMp6zz6aEmB7GihfDga0I',
//     appId: '1:434901720615:android:c469f69ca12a8014367802',
//     messagingSenderId: '434901720615',
//     projectId: 'spruce-9bb34',
//     databaseURL: 'https://spruce-9bb34.firebaseio.com',
//     storageBucket: 'spruce-9bb34.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBcxQO3NT85huG5oJw_b0qp1y9DkFN63C8',
//     appId: '1:434901720615:ios:a3cd39b5a7312cf6367802',
//     messagingSenderId: '434901720615',
//     projectId: 'spruce-9bb34',
//     databaseURL: 'https://spruce-9bb34.firebaseio.com',
//     storageBucket: 'spruce-9bb34.firebasestorage.app',
//     iosBundleId: 'com.absolin.spruceEngineeringPMS',
//   );
// }
